### ISSUE TITLE
Unable to get access to admin panel ... could you please guide me how to get access i am getting error

### ISSUE THREAD

**Issue by HarshalShende** [Devzstudio/BloodBank#3]

**Comment by PJijin** [comment]
Send screenshot of the error.

**Comment by HarshalShende** [comment]
I resolved the issue of admin login by manually setting the user as admin( is_admin=1) .. because there is no option to register as admin if I select to register as donor Yes Or No in both cases I am registered as a donor.  Now I am  **getting an error on the page who needs blood** 

![localhost_8000_who-needs-blood](https://user-images.githubusercontent.com/26615635/74584042-c9d44380-4ff3-11ea-92b5-caa22a8e3460.png)

**Comment by HarshalShende** [comment]
> Send screenshot of the error.



> I resolved the issue of admin login by manually setting the user as admin( is_admin=1) .. because there is no option to register as admin if I select to register as donor Yes Or No in both cases I am registered as a donor. Now I am **getting an error on the page who needs blood**
> 
> ![localhost_8000_who-needs-blood](https://user-images.githubusercontent.com/26615635/74584042-c9d44380-4ff3-11ea-92b5-caa22a8e3460.png)

**Comment by PJijin** [comment]
Can't find any count on who needs blood page. Try adding some record.

**Comment by HarshalShende** [comment]
But what if only one patient wants the blood then project will fail

**Comment by PJijin** [comment]
Send a pull request if you got the issue.

**Comment by HarshalShende** [comment]
> Send a pull request if you got the issue.

I want to save images of donor and fetch them in donors section

**Comment by PJijin** [comment]
You can add the feature and make pull request. No new features are added at the moment.

**Comment by HarshalShende** [comment]
Ok Sure I started working on this
